---
- name: execute role to prepare for rootless container deployment
  hosts: all
  gather_facts: false
  become: yes
  vars_files:
    - logstash_vars.yml
    - secrets.yml
  roles:
    - container_deploy