---
# tasks file for createmm

- name: quick debug task
  debug:
    msg: "{{container_user_password}}"

- name: create the {{container_user}} user with a UID of {{container_user_UID}}
  ansible.builtin.user:
    name: "{{container_user}}"
    uid: "{{ container_user_UID }}"
    system: true
    createhome: false
    state: present

- name: create directories {{host_dirs}}
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: "{{container_user}}"
    group: "{{container_user}}"
    mode: 0644
  loop: "{{host_dirs}}"

- name: set the selinux contexts of {{ host_dirs }} to container_file_t
  community.general.sefcontext:
    target: "{{ item }}"
    setype: container_file_t
    state: present
  loop: "{{host_dirs}}"

- name: run restorecon against mm_dirs
  ansible.builtin.command: restorecon -R -v "{{ item }}"
  loop: "{{host_dirs}}"

- name: open ports":"" "{{host_ports}}"
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop: "{{ host_ports }}"

- name: create port mappings
  set_fact: 
    port_mappings: "{{volume_mappings | default([]) + [item.0 + ':' + item.1 + '/tcp']}}"
  with_together:
    - "{{host_ports}}"
    - "{{container_ports}}"

- name: port mappings for host:container are":"
  debug:
    msg: "{{port_mappings}}"

- name: create volume mappings
  set_fact: 
    volume_mappings: "{{volume_mappings | default([]) + [item.0 + ':' + item.1 + ':Z']}}"
  with_together:
    - "{{host_dirs}}"
    - "{{container_dirs}}"

- name: volume mappings for host:container:option are":"
  debug:
    msg: "{{volume_mappings}}"

- name: deploy the karsten13/magicmirror container  using podman
  containers.podman.podman_container:
    name: magicmirror
    image: karsten13/magicmirror:latest
    state: started
    publish:
      - "{{ port_mappings[0] | default('') }}"
      - "{{ port_mappings[1] | default('') }}"
      - "{{ port_mappings[2] | default('') }}"
      - "{{ port_mappings[3] | default('') }}"
      - "{{ port_mappings[4] | default('') }}"
    volume:
      - "{{ volume_mappings[0] | default('') }}"
      - "{{ volume_mappings[1] | default('') }}"
      - "{{ volume_mappings[2] | default('') }}"
      - "{{ volume_mappings[3] | default('') }}"
      - "{{ volume_mappings[4] | default('') }}"
  register: result
  retries: 3
  delay: 1
  until: result is not failed


#- name: use podman to deploy the container